name: No trigger file paths
on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/ci-skip.yml
      - .gitignore
  pull_request:
    paths-ignore:
      - .github/workflows/ci-skip.yml
      - .gitignore

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: No trigger path triggered for required verify workflow.
        run: exit 0
